# Site settings
title: React
email: nackchuna@yeah.net
description: Tutorial to React
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "img" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: NackchunA
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/NackchunA/nackchuna.github.io
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/NackchunA/nackchuna.github.io
#########################################
# for duoshuo.com commentin system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: NackchunA
#duoshuo_url: "http://nackchuna.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: NackchunA
disqus_url: "http://nackchuna.github.io"
#########################################

# Build settings
markdown: kramdown

defaults:
  - scope:
        path: "assets/img"
    values:
        image: true


# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
